services:
  frontend:
    image: shubhamchau/td-frontend:v1
    ports:
      - "80:80"
  backend:
    image: shubhamchau/td-backend:v1
    environment:
      - PORT=8080
      - CLOUD_NAME=dtzbvvuiw
      - API_KEY=684557838481299
      - API_SECRET=Kpyoqacloyuhu9gNnodTg5KZCOk
      - SECRET=sc
      - DB=mongodb://database:27017/techdome
    ports:
      - "8080:8080"
  database:
    image: mongo:latest
    volumes: 
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local